### ISSUE TITLE
Can't open buttercup.pw subdirectories

### ISSUE THREAD

**Issue by tdislay** [buttercup/buttercup-website#70] opened 2023-04-29 20:40 UTC
If you try to open `https://buttercup.pw/privacy` or `https://buttercup.pw/auth/google` (this is the one causing buttercup/buttercup-mobile#337) you will end up with this error: `Application error: a client-side exception has occurred (see the browser console for more information).`

This is due to a 404 error while requesting the html document.
From what I've understood (a0fc87e1390c941e020af8d867195b515eae19c9) you've changed the host from AWS S3 to something else.. It may be the source of the issue..

Not having the issue in local environment.
So I don't think I can help

Happy fixing :)

**Comment by perry-mitchell** [comment] 2023-05-02 15:28
Thank you! Will prioritise this today. Didn't pay enough attention to the root cause, I think you're right on the money regarding the move.

**Comment by perry-mitchell** [comment] 2023-05-02 18:29
Not sure what the problem is here. The Digital Ocean app, where I migrated it to, isn't routing correctly for some reason. I'm debugging it as we speak but there's not much to go on I'm afraid.

**Comment by perry-mitchell** [comment] 2023-05-02 18:49
Seems this was fixed by 0f8da82577c1fbad0df14f59df8742c9349643fc - closing.

**Closed as completed by perry-mitchell** 2023-05-02 18:49 UTC
